[package]
name = "shaloop"
version = "0.1.0"
authors = ["Pierre Tholoniat <pierre@tholoniat.com>"]
edition = "2018"

[dependencies]
sha2 = "0.9.1"
maturin = "0.8.2"

[lib]
name = "shaloop"
crate-type = ["cdylib"]