name: MacOS Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install setuptools wheel twine auditwheel
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        brew install openssl
        echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile
        export LDFLAGS="-L/usr/local/opt/openssl/lib"
        export CPPFLAGS="-I/usr/local/opt/openssl/include"
        # ln -s /usr/local/opt/openssl/include/openssl /usr/local/include
        pip install -r requirements.txt
        # fetch third party libraries
        # git submodule init && git submodule update
        # pip wheel . -w wheel/
        # twine upload wheel/*
        python setup.py sdist bdist_wheel
        twine upload dist/*