name: Linux Package
# Adapted from: https://hub.docker.com/r/konstin2/maturin/dockerfile

on:
  release:
    types: [created]

jobs:
  deploy:
    strategy:
      matrix:
        python-version:
          - cp36-cp36m
          - cp37-cp37m
          - cp38-cp38

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Set path
        run: |
          echo "::add-path::/opt/python/${{ matrix.python-version }}/bin"
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          echo "::add-path::$HOME/.cargo/bin"
      - name: Python packages
        run: |
          python -m pip install --no-cache-dir cffi maturin
      - name: Publish with Maturin
        run: |
          maturin publish -b cffi --interpreter --manylinux 2010 -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
